"""
Content for the two-sheet Macro workbook.

INDICATORS  -> Sheet 1 "Macro Indicator Impact Library" (a professional cheat
sheet). Impact columns describe the USUAL first-order market reaction to a
HIGHER-than-expected print (for data), a RISE (for market gauges), or an
ESCALATION (for geopolitical risks). Arrows: ↑ up/supportive · ↓ down/negative ·
↔ neutral · Mixed = depends on context.

COMPONENTS  -> Sheet 2 "Global Stress / Fear Index" (a 0-100 composite).

Everything is editable input the analyst can tune.
"""

from __future__ import annotations

_INV = {"↑": "↓", "↓": "↑", "↑↑": "↓↓", "↓↓": "↑↑", "↔": "↔", "Mixed": "Mixed"}


def I(cat, ind, region, meas, why, hi, lo, react, exc, note, *,
      infl="↔", grow="↔", fed="Neutral", usd="↔", yld="↔", bond=None,
      gold="↔", oil="↔", eq="↔", em="↔", gcc="↔", conf="Medium"):
    """One library row. `bond` defaults to the inverse of `yld` (price vs yield)."""
    if bond is None:
        bond = _INV.get(yld, "↔")
    return dict(cat=cat, ind=ind, region=region, meas=meas, why=why, hi=hi, lo=lo,
                infl=infl, grow=grow, fed=fed, usd=usd, yld=yld, bond=bond, gold=gold,
                oil=oil, eq=eq, em=em, gcc=gcc, react=react, exc=exc, conf=conf, note=note)


INDICATORS = [
    # ---------------- US Inflation ----------------
    I("US Inflation", "CPI", "US", "headline consumer price inflation",
      "the most watched inflation gauge; drives Fed and real yields",
      "hotter inflation, hawkish", "cooler inflation, dovish",
      "Hot print → USD & yields up, bonds/gold/equities down", "Watch core vs headline; energy base effects distort",
      "The single biggest scheduled market mover alongside payrolls.",
      infl="↑", grow="↔", fed="Hawkish", usd="↑", yld="↑", gold="↓", oil="↔", eq="↓", em="↓", gcc="↔", conf="High"),
    I("US Inflation", "Core CPI", "US", "CPI excluding food and energy",
      "cleaner inflation trend the Fed targets", "sticky inflation, hawkish", "disinflation, dovish",
      "Sticky core → rates repriced higher, risk-off", "Shelter lags; supercore services is the tell",
      "More signal than headline for the Fed path.",
      infl="↑", fed="Hawkish", usd="↑", yld="↑", gold="↓", eq="↓", em="↓", conf="High"),
    I("US Inflation", "PCE", "US", "personal consumption expenditures price index",
      "broad inflation across a wide basket", "hawkish", "dovish",
      "Hot → hawkish repricing", "Broader basket than CPI", "Released later than CPI, so less surprise.",
      infl="↑", fed="Hawkish", usd="↑", yld="↑", gold="↓", eq="↓", conf="High"),
    I("US Inflation", "Core PCE", "US", "PCE excluding food and energy",
      "the Fed's PREFERRED inflation gauge (2% target)", "above target, hawkish", "toward target, dovish",
      "The number the Fed actually targets", "2% is the reference line", "Best single read on Fed comfort.",
      infl="↑", fed="Hawkish", usd="↑", yld="↑", gold="↓", eq="↓", conf="High"),
    I("US Inflation", "Inflation Expectations", "US", "survey/market expected future inflation",
      "the Fed fears un-anchoring of expectations", "hawkish, un-anchoring risk", "dovish, anchored",
      "Rising expectations → hawkish, gold mixed", "UMich 5-10y and 5y5y breakevens matter most",
      "A jump here alarms the Fed more than one hot print.",
      infl="↑", fed="Hawkish", usd="↑", yld="↑", gold="Mixed", eq="↓", conf="Medium"),
    # ---------------- US Labor ----------------
    I("US Labor", "Nonfarm Payrolls", "US", "net new jobs excluding farming",
      "the top labor print; jobs = income = demand", "strong jobs, hawkish", "weak jobs, dovish (or recession fear)",
      "Strong → USD & yields up; equities mixed", "Revisions and household survey can flip it",
      "With CPI, the biggest scheduled mover.",
      infl="↑", grow="↑", fed="Hawkish", usd="↑", yld="↑", gold="↓", oil="↑", eq="Mixed", em="↓", conf="High"),
    I("US Labor", "Unemployment Rate", "US", "share of labor force unemployed",
      "the Fed's employment mandate; a recession trigger", "higher = dovish, growth-negative",
      "lower = hawkish, tight labor", "Higher unemployment → dovish, bonds bid, equities mixed",
      "Read with participation and payrolls (Sahm rule)",
      "A rising trend is a classic late-cycle warning.",
      infl="↓", grow="↓", fed="Dovish", usd="↓", yld="↓", gold="↑", oil="↓", eq="Mixed", em="↑", conf="High"),
    I("US Labor", "Average Hourly Earnings", "US", "wage growth",
      "wages feed services inflation the Fed fears", "hot wages, hawkish", "cooling wages, dovish",
      "Hot wages → hawkish, bonds down", "Job-mix composition can mislead", "Key inflation-persistence signal.",
      infl="↑", grow="↑", fed="Hawkish", usd="↑", yld="↑", gold="↓", eq="↓", conf="High"),
    I("US Labor", "Initial Jobless Claims", "US", "new unemployment filings (weekly)",
      "the most timely labor signal", "rising claims = dovish, labor weakening",
      "falling claims = hawkish, labor strong", "Rising claims → dovish, bonds bid",
      "Noisy weekly; watch 4-week average", "First place labor cracks show up.",
      infl="↓", grow="↓", fed="Dovish", usd="↓", yld="↓", gold="↑", eq="Mixed", conf="Medium"),
    I("US Labor", "Continuing Claims", "US", "people still receiving benefits",
      "how hard it is to find a new job", "rising = labor loosening, dovish", "falling = labor tight, hawkish",
      "Rising trend → dovish, recession watch", "Confirms the initial-claims trend",
      "Sticky continuing claims signal slower re-hiring.",
      infl="↓", grow="↓", fed="Dovish", usd="↓", yld="↓", gold="↑", eq="Mixed", conf="Medium"),
    # ---------------- US Growth ----------------
    I("US Growth", "GDP", "US", "real output growth (annualized)",
      "headline growth; expansion vs recession", "strong growth, mildly hawkish", "weak growth, recession fear",
      "Strong → risk-on but can delay cuts", "Backward-looking; watch composition",
      "Big miss on the downside is a recession scare.",
      infl="↔", grow="↑", fed="Mixed", usd="↑", yld="↑", gold="↔", oil="↑", eq="↑", em="↑", gcc="↑", conf="High"),
    I("US Growth", "Retail Sales", "US", "consumer spending",
      "the consumer is the US growth engine", "strong consumer, growth+", "weak consumer, growth-",
      "Strong → growth+, can delay cuts", "Control group and autos/gas swings matter",
      "Consumer resilience keeps the Fed cautious.",
      infl="↑", grow="↑", fed="Mixed", usd="↑", yld="↑", gold="↔", oil="↑", eq="↑", em="↑", conf="High"),
    I("US Growth", "ISM Manufacturing", "US", "factory activity (>50 = expansion)",
      "a leading cyclical gauge", "expansion, risk-on", "contraction, growth fear",
      "Above 50 → risk-on; prices-paid = inflation tell", "Manufacturing is a small share of US GDP",
      "The prices-paid sub-index previews goods inflation.",
      infl="↑", grow="↑", fed="Mixed", usd="↑", yld="↑", oil="↑", eq="↑", em="↑", gcc="↑", conf="High"),
    I("US Growth", "ISM Services", "US", "services activity (>50 = expansion)",
      "services are ~70% of the US economy", "firm services, hawkish", "soft services, dovish",
      "Firm → hawkish, risk-on", "More important than manufacturing for the US cycle",
      "The single best monthly read on the US cycle.",
      infl="↑", grow="↑", fed="Hawkish", usd="↑", yld="↑", oil="↑", eq="↑", em="↑", conf="High"),
    I("US Growth", "PMI Manufacturing", "US", "S&P Global factory survey",
      "timely, globally comparable", "expansion, risk-on", "contraction, risk-off",
      "Above 50 → risk-on", "Flash vs final; differs from ISM", "Cross-country comparable cyclical read.",
      infl="↑", grow="↑", fed="Mixed", usd="↑", yld="↑", eq="↑", em="↑", conf="Medium"),
    I("US Growth", "PMI Services", "US", "S&P Global services survey",
      "broad private-sector activity", "expansion, risk-on", "contraction, risk-off",
      "Above 50 → risk-on", "Flash vs final revisions", "Confirms the services cycle.",
      infl="↑", grow="↑", fed="Mixed", usd="↑", yld="↑", eq="↑", em="↑", conf="Medium"),
    I("US Growth", "Durable Goods Orders", "US", "orders for long-lived goods",
      "business investment gauge", "strong orders, growth+", "weak orders, slowdown",
      "Strong → growth+", "Aircraft makes it lumpy; watch ex-transport", "Ex-transport core capex is the signal.",
      grow="↑", fed="Neutral", usd="↑", yld="↑", eq="↑", conf="Low"),
    I("US Growth", "Factory Orders", "US", "new orders at US factories",
      "forward demand for goods", "strong, growth+", "weak, slowdown",
      "Strong → mild growth+", "Lagging and volatile", "Secondary confirmation of manufacturing demand.",
      grow="↑", usd="↔", yld="↑", eq="↑", conf="Low"),
    I("US Growth", "Personal Income", "US", "household income",
      "fuel for future spending", "rising income, growth+", "falling income, growth-",
      "Rising → supports spending", "Transfer payments can distort", "Feeds the spending/savings picture.",
      grow="↑", usd="↔", yld="↔", eq="↑", conf="Low"),
    I("US Growth", "Personal Spending", "US", "household consumption",
      "the demand side of the economy", "strong spending, growth+", "weak spending, growth-",
      "Strong → growth+, mildly hawkish", "Paired with the PCE price data", "Real spending drives GDP nowcasts.",
      infl="↑", grow="↑", fed="Mixed", usd="↑", yld="↑", eq="↑", conf="Medium"),
    # ---------------- US Sentiment ----------------
    I("US Sentiment", "Consumer Confidence", "US", "Conference Board household sentiment",
      "leading indicator of spending", "confident, growth+", "worried, growth-",
      "Higher → mild growth+", "Labor-differential sub-index is useful", "Sentiment and spending can diverge.",
      grow="↑", usd="↔", yld="↔", eq="↑", conf="Medium"),
    I("US Sentiment", "UMich Sentiment", "US", "University of Michigan survey",
      "sentiment plus inflation expectations", "higher confidence, growth+", "lower, growth-",
      "Watch the inflation-expectations sub-index", "Politics can skew the headline",
      "The expectations component moves the Fed more than the mood.",
      grow="↑", infl="Mixed", usd="↔", eq="↑", conf="Medium"),
    # ---------------- US Housing ----------------
    I("US Housing", "Housing Starts", "US", "new residential construction begun",
      "rate-sensitive cyclical", "more building, growth+", "fewer, slowdown",
      "Higher → mild growth+", "Very sensitive to mortgage rates and weather", "An early read on rate transmission.",
      grow="↑", usd="↔", yld="↔", eq="↑", conf="Low"),
    I("US Housing", "Building Permits", "US", "permits to build (forward pipeline)",
      "leads starts by a month or two", "more permits, growth+", "fewer, slowdown",
      "Higher → forward growth+", "Leading vs starts", "Cleaner forward signal than starts.",
      grow="↑", usd="↔", yld="↔", eq="↑", conf="Low"),
    I("US Housing", "Existing Home Sales", "US", "closed sales of existing homes",
      "~90% of the housing market", "strong sales, growth+", "weak sales, slowdown",
      "Higher → growth+", "Rate-lock effect freezes supply", "Affordability and rates dominate.",
      grow="↑", usd="↔", yld="↔", eq="↔", conf="Low"),
    I("US Housing", "New Home Sales", "US", "sales of newly built homes",
      "direct demand for construction", "strong, growth+", "weak, slowdown",
      "Higher → growth+", "Small and volatile series", "Builder-sensitive; noisy month to month.",
      grow="↑", usd="↔", yld="↔", eq="↔", conf="Low"),
    # ---------------- US External / Fiscal ----------------
    I("US External", "Trade Balance", "US", "exports minus imports",
      "growth composition and USD flows", "smaller deficit, mild USD+", "wider deficit, mild USD-",
      "Wider deficit → mild USD headwind", "Usually a deficit; watch the trend", "Slow-moving; rarely a big mover.",
      grow="↔", usd="Mixed", yld="↔", conf="Low"),
    I("US Fiscal", "Fiscal Deficit", "US", "government spending minus revenue",
      "Treasury supply and term premium", "bigger deficit → more bond supply, yields up",
      "smaller deficit → supportive for bonds", "Wider deficit → higher term premium, bonds down",
      "Seasonal; watch the 12-month trend", "Supply is a growing driver of long-end yields.",
      infl="↑", fed="Neutral", usd="Mixed", yld="↑", gold="↑", eq="↔", conf="Medium"),
    I("US Fiscal", "Treasury Auctions", "US", "government bond issuance events",
      "gauge of demand for US debt", "strong demand (low tail) → bonds up",
      "weak demand (big tail) → bonds down, yields up", "Weak auction → yields up, risk-off",
      "Watch bid-to-cover, tails, indirect bidders", "Poor long-end auctions can spook risk assets.",
      usd="Mixed", yld="Mixed", gold="↔", eq="Mixed", conf="Medium"),
    # ---------------- US Fed / Policy ----------------
    I("US Fed", "FOMC Decision", "US", "the rate decision and statement",
      "sets the policy rate and tone", "hawkish surprise → tightening", "dovish surprise → easing",
      "Hawkish → USD & yields up, equities down", "The statement wording matters as much as the rate",
      "The main scheduled policy event.",
      fed="Mixed", usd="↑", yld="↑", gold="↓", eq="↓", em="↓", gcc="↔", conf="High"),
    I("US Fed", "Dot Plot", "US", "FOMC members' rate projections",
      "signals the expected policy path", "higher dots → hawkish", "lower dots → dovish",
      "Higher dots → repricing of cuts, risk-off", "It is a projection, not a promise",
      "Shifts the whole curve when it moves.",
      fed="Mixed", usd="↑", yld="↑", gold="↓", eq="↓", conf="High"),
    I("US Fed", "Fed Minutes", "US", "detailed record of the FOMC meeting",
      "colour on the debate and risks", "hawkish tone → tightening bias", "dovish tone → easing bias",
      "Hawkish minutes → yields up", "3 weeks old; can be stale vs newer data", "Watch for split/consensus language.",
      fed="Mixed", usd="↑", yld="↑", eq="Mixed", conf="Medium"),
    I("US Fed", "Fed Speeches", "US", "public remarks by Fed officials",
      "real-time policy guidance between meetings", "hawkish comments → tightening", "dovish comments → easing",
      "Chair/known voters move markets most", "Distinguish voters from non-voters; hawks from doves",
      "Can reprice the front end intraday.",
      fed="Mixed", usd="↑", yld="↑", eq="Mixed", conf="Medium"),
    # ---------------- Rates / FX market ----------------
    I("Rates/FX", "DXY (US Dollar Index)", "US", "USD vs a basket of major currencies",
      "the world's funding and safe-haven currency", "USD strengthening", "USD weakening",
      "Stronger USD → headwind for commodities, EM, gold", "Rises on both Fed hawkishness AND safe-haven demand",
      "A strong-USD regime tightens global conditions.",
      infl="Mixed", fed="↔", usd="↑↑", yld="↔", gold="↓", oil="↓", eq="Mixed", em="↓", gcc="↔", conf="High"),
    I("Rates/FX", "US 2Y Yield", "US", "2-year Treasury yield",
      "the market's read of the Fed path", "rising → hawkish repricing", "falling → dovish repricing",
      "2Y up → front-end tightening, equities pressured", "Most sensitive to Fed expectations",
      "The cleanest gauge of expected policy.",
      fed="Mixed", usd="↑", yld="↑", bond="↓", gold="↓", eq="↓", em="↓", conf="High"),
    I("Rates/FX", "US 10Y Yield", "US", "10-year Treasury yield",
      "the global risk-free discount rate", "rising → higher discount rate", "falling → lower discount rate",
      "10Y up → pressures equities (esp. growth), USD up", "Driven by growth, inflation, term premium, supply",
      "The anchor for global asset valuation.",
      infl="Mixed", fed="↔", usd="↑", yld="↑", bond="↓", gold="↓", eq="↓", em="↓", gcc="↔", conf="High"),
    I("Rates/FX", "Yield Curve 2s10s", "US", "10Y minus 2Y spread",
      "recession and cycle signal", "steepening → growth/inflation or Fed cuts",
      "inversion → recession warning", "Deep inversion → late-cycle caution",
      "Steepening can be bull (cuts) or bear (supply)", "Read the driver, not just the sign.",
      grow="Mixed", fed="Mixed", eq="Mixed", conf="Medium"),
    I("Rates/FX", "Real Yields", "US", "TIPS yields (nominal minus inflation)",
      "the true cost of capital", "rising real yields → tighter conditions", "falling → easier conditions",
      "Rising real yields → gold & long-duration equities down", "The key driver of gold over time",
      "Gold's biggest headwind is rising real yields.",
      fed="↔", usd="↑", yld="↑", bond="↓", gold="↓↓", eq="↓", em="↓", conf="High"),
    I("Rates/FX", "Breakeven Inflation", "US", "market-implied inflation (nominal minus TIPS)",
      "the market's inflation forecast", "rising → inflation priced up", "falling → disinflation priced",
      "Rising breakevens → gold up, hawkish risk", "Watch 5y and 5y5y forward",
      "A market vote on the inflation path.",
      infl="↑", fed="Hawkish", usd="Mixed", yld="↑", gold="↑", oil="↑", conf="Medium"),
    # ---------------- Volatility / Credit ----------------
    I("Volatility", "VIX", "US", "S&P 500 30-day implied volatility",
      "the equity 'fear gauge'", "spiking → fear, risk-off", "falling → calm, risk-on",
      "VIX spike → risk-off, safe havens bid", ">30 = fear, >40 = panic; can stay low then gap",
      "The headline risk-on/risk-off switch.",
      fed="Dovish", usd="↑", yld="↓", bond="↑", gold="↑", oil="↓", eq="↓↓", em="↓", gcc="↓", conf="High"),
    I("Volatility", "MOVE Index", "US", "Treasury market implied volatility",
      "the bond-market 'fear gauge'", "rising → rates stress", "falling → rates calm",
      "High MOVE → funding stress, wider spreads", "Often leads equity vol and credit stress",
      "Elevated MOVE tightens financial conditions broadly.",
      fed="↔", usd="↑", yld="Mixed", bond="↓", gold="↑", eq="↓", em="↓", conf="Medium"),
    I("Credit", "Credit Spreads", "Global", "corporate yield over Treasuries (IG/HY)",
      "funding stress and default risk", "widening → stress, risk-off", "tightening → calm, risk-on",
      "Widening spreads → risk-off, equities down", "HY OAS is the sharper stress signal",
      "The clearest market gauge of credit stress.",
      fed="Dovish", usd="↑", yld="↓", bond="↑", gold="↑", oil="↓", eq="↓", em="↓", gcc="↓", conf="High"),
    # ---------------- Equity market ----------------
    I("Equity", "S&P 500", "US", "large-cap US equity benchmark",
      "the core risk-asset barometer", "rising → risk-on", "falling → risk-off",
      "Drawdowns → flight to USD, Treasuries, gold", "Concentration in mega-cap tech skews it",
      "The reference for global risk appetite.",
      fed="↔", usd="Mixed", yld="Mixed", gold="↔", eq="↑↑", em="↑", gcc="↑", conf="High"),
    I("Equity", "Nasdaq", "US", "tech-heavy US equity index",
      "long-duration, rate-sensitive equities", "rising → risk-on, easy conditions", "falling → risk-off",
      "Very sensitive to real yields", "Duration means it falls hard when yields spike",
      "The high-beta expression of risk appetite.",
      fed="↔", usd="Mixed", yld="Mixed", gold="↔", eq="↑↑", em="↑", conf="Medium"),
    # ---------------- Commodities ----------------
    I("Commodities", "Gold", "Global", "the classic safe-haven metal",
      "hedge against risk, inflation and real-yield moves", "rising → hedging/inflation demand",
      "falling → risk-on or real-yields up", "Rises on risk-off & falling real yields; falls when USD/real yields rise",
      "Can rise on geopolitics yet fall if USD and real yields jump", "Trades off real yields and USD, not just fear.",
      infl="↑", usd="Mixed", yld="Mixed", gold="↑↑", eq="↔", gcc="↔", conf="High"),
    I("Commodities", "Brent Oil", "Global", "global crude benchmark",
      "inflation, growth and geopolitics in one price", "supply/geo spike → inflationary, risk-off; demand rise → growth+",
      "falling → disinflation or demand weakness", "Cause matters: supply shock vs demand strength",
      "Supply-driven rallies hurt risk; demand-driven help it", "Read WHY oil moved before drawing conclusions.",
      infl="↑", grow="Mixed", fed="Hawkish", usd="↔", yld="↑", gold="↑", oil="↑↑", eq="Mixed", em="Mixed",
      gcc="↑", conf="High"),
    I("Commodities", "WTI Oil", "US", "US crude benchmark",
      "US energy prices and shale economics", "rising → higher pump/inflation", "falling → cheaper energy",
      "Same logic as Brent; watch the Brent-WTI spread", "US-specific supply and pipeline dynamics",
      "Domestic inflation read; GCC follows Brent more.",
      infl="↑", grow="Mixed", fed="Hawkish", usd="↔", yld="↑", gold="↑", oil="↑↑", eq="Mixed", gcc="↑", conf="High"),
    # ---------------- Geopolitical ----------------
    I("Geopolitical", "OPEC+ Decisions", "GCC/Global", "OPEC+ production quota changes",
      "sets global oil supply at the margin", "cuts → oil up, inflationary", "hikes → oil down, disinflationary",
      "Surprise cut → oil & inflation up, GCC revenue up", "Compliance and spare capacity vary",
      "Directly drives the GCC fiscal backdrop.",
      infl="↑", fed="Hawkish", usd="↔", yld="↑", gold="↑", oil="↑↑", eq="↓", gcc="↑", conf="High"),
    I("Geopolitical", "Oil Inventories", "US", "weekly EIA crude stock change",
      "near-term oil supply/demand balance", "builds → bearish oil", "draws → bullish oil",
      "Big draw → oil up, inflationary", "Very noisy weekly; watch the trend", "Short-term oil driver only.",
      infl="Mixed", oil="↓", gcc="↓", gold="↔", conf="Low"),
    I("Geopolitical", "Iran / Gulf Tension", "Middle East", "conflict risk around Iran and the Gulf",
      "threatens Gulf oil supply and shipping", "escalation → oil & risk premium up",
      "de-escalation → oil & risk premium down", "Escalation → oil spike, risk-off, gold up",
      "Direct threat to GCC; watch the oil-supply channel", "The most oil-sensitive geopolitical risk for you.",
      infl="↑", fed="Mixed", usd="↑", yld="Mixed", gold="↑", oil="↑↑", eq="↓", em="↓", gcc="↓", conf="Medium"),
    I("Geopolitical", "Strait of Hormuz Risk", "Middle East", "threat to the key oil-transit chokepoint",
      "~20% of global oil passes through it", "rising threat → large oil premium",
      "easing → premium unwinds", "Closure fear → oil spikes, global risk-off",
      "Even a partial disruption is a major supply shock", "Tail risk with outsized oil impact.",
      infl="↑↑", fed="Mixed", usd="↑", yld="Mixed", gold="↑", oil="↑↑", eq="↓", em="↓", gcc="↓", conf="Medium"),
    I("Geopolitical", "Ukraine / Russia", "Europe", "war escalation risk",
      "energy, grain and European security", "escalation → energy up, risk-off",
      "ceasefire → risk-on, energy down", "Escalation → gas/oil & gold up, EU risk-off",
      "European gas and grain are the main channels", "Less direct for GCC than Gulf risks.",
      infl="↑", usd="↑", yld="Mixed", gold="↑", oil="↑", eq="↓", em="↓", gcc="↔", conf="Medium"),
    I("Geopolitical", "China / Taiwan", "Asia", "cross-strait conflict risk",
      "tech supply chains and global trade", "escalation → global risk-off, tech hit",
      "de-escalation → risk-on", "Escalation → severe risk-off, semis & trade hit",
      "Low probability but very high impact", "A global tail risk, not just Asian.",
      grow="↓", usd="↑", yld="↓", gold="↑", oil="↑", eq="↓↓", em="↓↓", gcc="↓", conf="Low"),
    I("Geopolitical", "Red Sea Shipping", "Middle East", "attacks disrupting Suez/Red Sea trade",
      "container freight and supply chains", "escalation → freight & goods inflation up",
      "easing → freight normalizes", "Disruption → longer routes, freight & inflation up",
      "Hits goods inflation and delivery times", "Watch freight rates and re-routing.",
      infl="↑", usd="↔", yld="↑", gold="↑", oil="↑", eq="↓", em="↓", gcc="Mixed", conf="Medium"),
    I("Geopolitical", "Sanctions", "Global", "trade/financial restrictions on states",
      "supply of oil, metals and goods", "new sanctions → supply tighter, prices up",
      "removal → supply eases", "Energy sanctions → oil up, inflationary", "Effect depends on enforcement and workarounds",
      "Commodity-supply channel is the key for markets.",
      infl="↑", usd="↑", yld="↔", gold="↑", oil="↑", eq="Mixed", em="↓", gcc="Mixed", conf="Low"),
    # ---------------- Global / International ----------------
    I("Global", "Global PMI", "Global", "world composite activity survey",
      "global demand, trade and commodities", "expansion → risk-on, commodities up",
      "contraction → risk-off", "Global upturn → oil, EM, GCC supported", "China's swing dominates the global cycle",
      "Best single read on the global cycle.",
      grow="↑", usd="↓", yld="↑", gold="↔", oil="↑", eq="↑", em="↑", gcc="↑", conf="Medium"),
    I("Global", "China GDP", "China", "China real growth",
      "the largest marginal source of commodity demand", "strong → commodities & EM up",
      "weak → risk-off, oil down", "Strong China → oil, EM, GCC up", "Official data quality is debated",
      "China demand is central to the GCC oil bid.",
      grow="↑", usd="↓", yld="↑", gold="↔", oil="↑", eq="↑", em="↑", gcc="↑", conf="Medium"),
    I("Global", "China Trade Data", "China", "China exports and imports",
      "global trade pulse and commodity appetite", "strong imports → commodity demand up",
      "weak → global demand fear", "Weak China imports → oil & EM down", "Lunar New Year seasonality distorts",
      "Imports proxy China's commodity appetite.",
      grow="↑", usd="↓", oil="↑", eq="↑", em="↑", gcc="↑", conf="Low"),
    I("Global", "Eurozone CPI", "Eurozone", "euro-area inflation",
      "drives ECB policy and EUR", "hot → ECB hawkish, EUR up (USD down)", "cool → ECB dovish, EUR down",
      "Hot EZ CPI → ECB hawkish, EUR up", "Country dispersion matters", "Main input to the ECB path and EUR/USD.",
      infl="↑", fed="Hawkish", usd="↓", yld="↑", gold="↔", eq="Mixed", conf="Medium"),
    I("Global", "ECB Policy", "Eurozone", "European Central Bank decisions",
      "euro-area rates and EUR/USD", "hawkish → EUR up, USD down", "dovish → EUR down, USD up",
      "Hawkish ECB → EUR up, bunds down", "EUR is the biggest DXY weight", "Second-most important CB for USD.",
      fed="Mixed", usd="↓", yld="↑", eq="Mixed", conf="Medium"),
    I("Global", "BOE Policy", "UK", "Bank of England decisions",
      "UK rates and GBP", "hawkish → GBP up", "dovish → GBP down",
      "Hawkish BOE → GBP up, gilts down", "UK inflation has been stickier", "Mainly a GBP and gilt driver.",
      fed="Mixed", usd="↓", yld="↑", eq="↔", conf="Low"),
    I("Global", "SNB Policy", "Switzerland", "Swiss National Bank decisions",
      "CHF, a key safe-haven currency", "hawkish/intervention → CHF up", "dovish → CHF down",
      "CHF strength signals risk-off demand", "SNB intervenes in FX directly",
      "CHF is a risk-off barometer alongside gold/JPY.",
      usd="Mixed", gold="↔", eq="↔", conf="Low"),
    I("Global", "BOJ Policy", "Japan", "Bank of Japan decisions",
      "JPY, global carry and rates", "hawkish (exit) → JPY up, global yields up",
      "dovish → JPY down, carry-on", "Hawkish BOJ → JPY up, unwind of carry trades",
      "Yen carry unwind can jolt global markets", "A hawkish surprise can trigger global de-risking.",
      fed="Mixed", usd="Mixed", yld="↑", gold="↔", eq="↓", em="↓", conf="Medium"),
]


def _c(name, desc, level, wk, mo, driver, normal, stress, weight, unit, comment):
    return dict(name=name, desc=desc, level=level, wk=wk, mo=mo, driver=driver,
                normal=normal, stress=stress, weight=weight, unit=unit, comment=comment)


# Sheet 2 components. driver: how the 0-100 score is computed
#   level     -> from Current level vs thresholds
#   move      -> from 1-month change vs thresholds (higher = more stress)
#   neg_move  -> from a FALL in the 1-month change (drawdown magnitude)
#   abs_move  -> from the absolute size of the 1-month change (a shock either way)
#   manual    -> Current level IS the 0-100 score (analyst set)
COMPONENTS = [
    _c("Equity fear (VIX)", "S&P 500 implied volatility", 24, 3, 6, "level", 15, 35, 0.18, "index",
       "Above 30 signals fear; above 40 panic."),
    _c("Bond volatility (MOVE)", "Treasury implied volatility", 115, 8, 15, "level", 90, 160, 0.12, "index",
       "Rising MOVE tightens financial conditions."),
    _c("USD strength (DXY)", "USD vs major currencies", 104.5, 0.8, 2.5, "move", 0, 4, 0.08, "% 1m",
       "A fast USD rally = global tightening / flight to safety."),
    _c("Safe-haven gold", "gold spot price", 2380, 1.5, 5.0, "move", 0, 10, 0.06, "% 1m",
       "Sharp gold rallies signal hedging demand."),
    _c("Oil shock (Brent)", "Brent crude", 88, 4.0, 9.0, "move", 0, 15, 0.10, "% 1m",
       "Supply/geo-driven spikes are inflationary and risk-negative."),
    _c("Equity drawdown (S&P 500)", "S&P 500 pullback", 5100, -1.5, -4.0, "neg_move", 0, 15, 0.15, "% 1m",
       "Drawdown magnitude from the recent high."),
    _c("Credit spreads (HY)", "high-yield OAS", 400, 20, 55, "level", 350, 800, 0.13, "bps",
       "Widening high-yield spreads = credit / funding stress."),
    _c("Rate shock (US 10Y)", "10-year Treasury yield move", 4.35, 10, 35, "abs_move", 0, 60, 0.08, "bps 1m",
       "Fast 10Y moves (up or down) destabilize markets."),
    _c("Geopolitical risk", "wars, Iran, Ukraine, Red Sea, Taiwan", 60, 5, 10, "manual", 0, 100, 0.10, "0-100",
       "Analyst score: 0 calm .. 100 crisis."),
]

STRESS_BANDS = [(20, "Calm"), (40, "Normal"), (60, "Elevated"), (80, "High Stress")]  # above 80 -> Crisis

BAND_INTERP = {
    "Calm": "Risk-on; volatility low. Supportive for equities, EM and carry; safe havens soften.",
    "Normal": "Balanced conditions; no broad market stress signal.",
    "Elevated": "Caution; risk-off pressure building. Favor quality, USD and safe havens; watch oil and GCC risk.",
    "High Stress": "Risk-off; deleveraging risk. Long USD, Treasuries and gold; reduce equities and EM.",
    "Crisis": "Acute stress; flight to safety. Preserve capital, hold cash/USTs/gold, cut risk exposure.",
}
BAND_PORTFOLIO = {
    "Calm": "Add risk selectively; equities and EM acceptable; keep some hedges.",
    "Normal": "Neutral positioning; no defensive tilt required.",
    "Elevated": "Trim risk; raise USD, gold and quality bonds. Higher oil aids GCC fiscal but geopolitics pressures GCC equities.",
    "High Stress": "Defensive: long USD, US Treasuries and gold; cut equities, EM and GCC risk exposure.",
    "Crisis": "Maximum defensive: cash, US Treasuries and gold; minimal risk assets; protect GCC/oil-linked exposure.",
}


def build_sample() -> dict:
    return {"indicators": INDICATORS, "components": COMPONENTS}


def empty_like_sample() -> dict:
    comps = []
    for c in COMPONENTS:
        c = dict(c)
        c.update(level=None, wk=None, mo=None, comment="")
        comps.append(c)
    return {"indicators": INDICATORS, "components": comps}
