"""
Sample dataset: "Helios Diversified Industries plc" (fictional).

Ten years of historical statements for a generic diversified industrial — chosen
so the engine reads as broadly applicable. Generated by an articulated
roll-forward (one hidden anchor year seeds the first displayed year), with equity
set as the exact integer plug so the historical balance sheet balances to the
unit. The forecast itself is built live in the workbook, not here.
"""

from __future__ import annotations

HIST_YEARS = 10
FCST_YEARS = 10


def build_sample() -> dict:
    n_disp = HIST_YEARS
    n = n_disp + 1                      # + hidden anchor at index 0
    r = lambda x: int(round(x))         # noqa: E731

    g = [0.06, 0.06, 0.05, 0.07, 0.05, 0.06, 0.05, 0.04, 0.05, 0.04, 0.04]
    revenue = [4200.0]
    for i in range(1, n):
        revenue.append(revenue[-1] * (1 + g[i]))

    def ramp(a, b):
        return [a + (b - a) * i / (n - 1) for i in range(n)]

    gm = ramp(0.340, 0.356)
    opex_p = ramp(0.196, 0.188)
    dep_p = 0.050
    capex_p = ramp(0.060, 0.052)
    dso, dio, dpo = 52, 70, 45
    oca_p, ocl_p = 0.03, 0.05
    tax_rate = 0.25
    int_rate = 0.050
    payout = 0.30

    intangibles = 600
    other_assets = 300
    other_liab = 250
    short_term_debt = 200
    long_term_debt = [1500, 1500, 1450, 1400, 1350, 1300, 1250, 1200, 1150, 1100, 1050]

    cash = [500.0]
    ppe = [2000.0]

    cogs = [0.0] * n
    gross = [0.0] * n
    opex = [0.0] * n
    ebitda = [0.0] * n
    dep = [0.0] * n
    ebit = [0.0] * n
    intexp = [0.0] * n
    pretax = [0.0] * n
    tax = [0.0] * n
    ni = [0.0] * n
    for i in range(n):
        gross[i] = revenue[i] * gm[i]
        cogs[i] = revenue[i] - gross[i]
        opex[i] = revenue[i] * opex_p[i]
        ebitda[i] = gross[i] - opex[i]
        dep[i] = revenue[i] * dep_p
        ebit[i] = ebitda[i] - dep[i]
        prior_debt = (short_term_debt + long_term_debt[i - 1]) if i else (short_term_debt + long_term_debt[i])
        intexp[i] = int_rate * prior_debt
        pretax[i] = ebit[i] - intexp[i]
        tax[i] = pretax[i] * tax_rate
        ni[i] = pretax[i] - tax[i]

    recv = [revenue[i] * dso / 365 for i in range(n)]
    inv = [cogs[i] * dio / 365 for i in range(n)]
    ap = [cogs[i] * dpo / 365 for i in range(n)]
    oca = [revenue[i] * oca_p for i in range(n)]
    ocl = [revenue[i] * ocl_p for i in range(n)]
    capex = [revenue[i] * capex_p[i] for i in range(n)]
    for i in range(1, n):
        ppe.append(ppe[i - 1] + capex[i] - dep[i])

    ocf = [0.0] * n
    div = [0.0] * n
    for i in range(1, n):
        d_wc = (recv[i] - recv[i - 1]) + (inv[i] - inv[i - 1]) + (oca[i] - oca[i - 1]) \
            - (ap[i] - ap[i - 1]) - (ocl[i] - ocl[i - 1])
        ocf[i] = ni[i] + dep[i] - d_wc
        div[i] = payout * ni[i]
        debt_chg = (short_term_debt + long_term_debt[i]) - (short_term_debt + long_term_debt[i - 1])
        net_chg = ocf[i] - capex[i] + (debt_chg - div[i])
        cash.append(cash[i - 1] + net_chg)

    disp = slice(1, n)
    yrs = list(range(2015, 2015 + n_disp))
    periods = [f"FY{y}" for y in yrs]

    def s(a):
        return [r(x) for x in a[disp]]

    cash_, ar_, inv_, oca_, ppe_ = (s(x) for x in (cash, recv, inv, oca, ppe))
    ap_, ltd_ = s(ap), [long_term_debt[i] for i in range(1, n)]
    # "Other liabilities" lumps the non-current base with current accruals (ocl).
    olt_ = [other_liab + s(ocl)[i] for i in range(n_disp)]
    equity_disp = [(cash_[i] + ar_[i] + inv_[i] + oca_[i] + ppe_[i] + intangibles + other_assets)
                   - (ap_[i] + short_term_debt + ltd_[i] + olt_[i]) for i in range(n_disp)]

    # integrity assertion
    for i in range(n_disp):
        a = cash_[i] + ar_[i] + inv_[i] + oca_[i] + ppe_[i] + intangibles + other_assets
        le = ap_[i] + short_term_debt + ltd_[i] + olt_[i] + equity_disp[i]
        assert a == le, f"BS imbalance yr {i}"

    series = {
        "revenue": s(revenue), "cogs": s(cogs), "opex": s(opex), "depreciation": s(dep),
        "interest_expense": s(intexp), "tax_expense": s(tax),
        "cash": cash_, "receivables": ar_, "inventory": inv_, "other_current_assets": oca_,
        "ppe": ppe_, "intangibles": [intangibles] * n_disp, "other_assets": [other_assets] * n_disp,
        "payables": ap_, "short_term_debt": [short_term_debt] * n_disp,
        "long_term_debt": ltd_, "other_liabilities": olt_,
        "equity": equity_disp,
        "operating_cash_flow": s(ocf), "capex": s(capex),
    }
    meta = {
        "name": "Helios Diversified Industries plc", "ticker": "HELI",
        "currency": "USD", "units": "millions", "fiscal_year_end": "31 December",
        "description": "Fictional diversified industrial used as a worked example; all figures illustrative.",
    }
    # Manual forecast assumptions by scenario: (Bear, Base, Bull).
    assumptions = {
        "rev_growth": (0.02, 0.045, 0.07), "gross_margin": (0.340, 0.356, 0.370),
        "ebitda_margin": (0.150, 0.168, 0.185), "tax_rate": (0.27, 0.25, 0.23),
        "dso": (58, 50, 45), "dio": (78, 68, 62), "dpo": (40, 46, 52),
        "capex_pct": (0.060, 0.052, 0.045), "da_pct": (0.050, 0.050, 0.050),
        "cash_pct": (0.060, 0.070, 0.080), "oa_pct": (0.045, 0.045, 0.045),
        "ol_pct": (0.086, 0.086, 0.086), "int_rate": (0.060, 0.050, 0.045),
        "dividend_payout": (0.20, 0.30, 0.35), "debt_repay_pct": (0.03, 0.05, 0.08),
        "new_debt": (0, 0, 0), "cash_yield": (0.010, 0.015, 0.020),
    }
    return {"meta": meta, "periods": periods, "series": series, "assumptions": assumptions,
            "hist_years": HIST_YEARS, "fcst_years": FCST_YEARS}


def empty_like_sample() -> dict:
    s = build_sample()
    series = {k: [None] * len(s["periods"]) for k in s["series"]}
    assumptions = {k: (None, None, None) for k in s["assumptions"]}
    meta = dict(s["meta"])
    meta.update(name="<Company name>", ticker="<TICKER>")
    return {"meta": meta, "periods": s["periods"], "series": series, "assumptions": assumptions,
            "hist_years": HIST_YEARS, "fcst_years": FCST_YEARS}


if __name__ == "__main__":
    d = build_sample()
    print("Built:", d["meta"]["name"], "| hist years:", len(d["periods"]))
    print("FY2024 revenue:", d["series"]["revenue"][-1], "| equity:", d["series"]["equity"][-1])
